# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Augustin.pelage/Desktop/Data_logger_v2.2/Impedance.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_impedance(object):
    def setupUi(self, MainWindow_impedance):
        MainWindow_impedance.setObjectName("MainWindow_impedance")
        MainWindow_impedance.setEnabled(True)
        MainWindow_impedance.resize(760, 430)
        MainWindow_impedance.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow_impedance)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 5, 720, 380))
        self.tabWidget.setMaximumSize(QtCore.QSize(740, 480))
        self.tabWidget.setBaseSize(QtCore.QSize(720, 480))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.spinBox_16 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_16.setGeometry(QtCore.QRect(640, 280, 61, 22))
        self.spinBox_16.setMinimum(-360)
        self.spinBox_16.setMaximum(360)
        self.spinBox_16.setProperty("value", -90)
        self.spinBox_16.setObjectName("spinBox_16")
        self.label_42 = QtWidgets.QLabel(self.tab_2)
        self.label_42.setGeometry(QtCore.QRect(630, 250, 81, 31))
        self.label_42.setObjectName("label_42")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(510, 20, 111, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(620, 300, 91, 31))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(530, 40, 71, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(200000000)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(230, 80, 491, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.spinBox_15 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_15.setGeometry(QtCore.QRect(570, 140, 51, 22))
        self.spinBox_15.setMinimum(-360)
        self.spinBox_15.setMaximum(360)
        self.spinBox_15.setProperty("value", 0)
        self.spinBox_15.setObjectName("spinBox_15")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(560, 110, 81, 31))
        self.label_20.setObjectName("label_20")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(340, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(440, 20, 81, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(450, 40, 61, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(630, 200, 81, 31))
        self.label_19.setObjectName("label_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setGeometry(QtCore.QRect(120, 70, 91, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setGeometry(QtCore.QRect(620, 40, 71, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(200000000)
        self.spinBox_2.setProperty("value", 60000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_4.setGeometry(QtCore.QRect(650, 330, 51, 22))
        self.spinBox_4.setMinimum(0)
        self.spinBox_4.setMaximum(200000000)
        self.spinBox_4.setProperty("value", 0)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_14 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_14.setGeometry(QtCore.QRect(640, 230, 61, 22))
        self.spinBox_14.setMinimum(-360)
        self.spinBox_14.setMaximum(360)
        self.spinBox_14.setProperty("value", 0)
        self.spinBox_14.setObjectName("spinBox_14")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(640, 110, 81, 31))
        self.label_36.setObjectName("label_36")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_3.setGeometry(QtCore.QRect(360, 40, 71, 22))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(200000000)
        self.spinBox_3.setProperty("value", 6000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_21.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(120, 30, 91, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(610, 20, 81, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_13 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_13.setGeometry(QtCore.QRect(650, 140, 51, 22))
        self.spinBox_13.setMinimum(-360)
        self.spinBox_13.setMaximum(360)
        self.spinBox_13.setProperty("value", 0)
        self.spinBox_13.setObjectName("spinBox_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.graphicsView = PlotWidget(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(20, 111, 541, 231))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_23.setGeometry(QtCore.QRect(230, 10, 101, 51))
        self.pushButton_23.setObjectName("pushButton_23")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow_impedance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_impedance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_impedance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_impedance)
        self.statusbar.setObjectName("statusbar")
        MainWindow_impedance.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_impedance)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_impedance)

    def retranslateUi(self, MainWindow_impedance):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_impedance.setWindowTitle(_translate("MainWindow_impedance", "MainWindow"))
        self.label_42.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Level 2, dB</p></body></html>"))
        self.label.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Start (kHz)</p></body></html>"))
        self.label_5.setText(_translate("MainWindow_impedance", "Freq. corr., ppb"))
        self.label_20.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Phase 2, deg</p></body></html>"))
        self.label_4.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Points</p></body></html>"))
        self.label_9.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Bandwidth</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow_impedance", "10000"))
        self.comboBox_2.setItemText(1, _translate("MainWindow_impedance", "5000"))
        self.comboBox_2.setItemText(2, _translate("MainWindow_impedance", "1000"))
        self.comboBox_2.setItemText(3, _translate("MainWindow_impedance", "500"))
        self.comboBox_2.setItemText(4, _translate("MainWindow_impedance", "100"))
        self.comboBox_2.setItemText(5, _translate("MainWindow_impedance", "50"))
        self.comboBox_2.setItemText(6, _translate("MainWindow_impedance", "10"))
        self.comboBox_2.setItemText(7, _translate("MainWindow_impedance", "5"))
        self.comboBox_2.setItemText(8, _translate("MainWindow_impedance", "1"))
        self.label_19.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Level 1, dB</p></body></html>"))
        self.pushButton_20.setText(_translate("MainWindow_impedance", "Load"))
        self.label_36.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Phase 1, deg</p></body></html>"))
        self.pushButton_21.setText(_translate("MainWindow_impedance", "Open"))
        self.pushButton_19.setText(_translate("MainWindow_impedance", "Short"))
        self.label_3.setText(_translate("MainWindow_impedance", "<html><head/><body><p align=\"center\">Stop (kHz)</p></body></html>"))
        self.pushButton_22.setText(_translate("MainWindow_impedance", "Single"))
        self.pushButton_23.setText(_translate("MainWindow_impedance", "Valider"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_impedance", "Impedance"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_impedance = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_impedance()
    ui.setupUi(MainWindow_impedance)
    MainWindow_impedance.show()
    sys.exit(app.exec_())
