# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/Augustin.pelage/Desktop/Data_logger_v2.2/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(760, 430)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 5, 720, 380))
        self.tabWidget.setMaximumSize(QtCore.QSize(740, 480))
        self.tabWidget.setBaseSize(QtCore.QSize(720, 480))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.line_7 = QtWidgets.QFrame(self.tab2)
        self.line_7.setGeometry(QtCore.QRect(380, 290, 331, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.progressBar_4 = QtWidgets.QProgressBar(self.tab2)
        self.progressBar_4.setGeometry(QtCore.QRect(0, 320, 341, 23))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 310, 111, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_8 = QtWidgets.QFrame(self.tab2)
        self.line_8.setGeometry(QtCore.QRect(190, 0, 20, 301))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.graphicsView_4 = PlotWidget(self.tab2)
        self.graphicsView_4.setGeometry(QtCore.QRect(170, 0, 541, 301))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_8.setGeometry(QtCore.QRect(600, 310, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.toolButton = QtWidgets.QToolButton(self.tab2)
        self.toolButton.setGeometry(QtCore.QRect(10, 240, 151, 31))
        self.toolButton.setObjectName("toolButton")
        self.comboBox = QtWidgets.QComboBox(self.tab2)
        self.comboBox.setGeometry(QtCore.QRect(10, 100, 151, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_18 = QtWidgets.QLabel(self.tab2)
        self.label_18.setGeometry(QtCore.QRect(70, 190, 51, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit = QtWidgets.QLineEdit(self.tab2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 210, 101, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.line_4 = QtWidgets.QFrame(self.tab2)
        self.line_4.setGeometry(QtCore.QRect(-3, 270, 171, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab2)
        self.line_5.setGeometry(QtCore.QRect(0, 180, 171, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab2)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 310, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 160, 151, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 16, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_3.setGeometry(QtCore.QRect(40, 40, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 10, 101, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 16, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab2)
        self.comboBox_5.setGeometry(QtCore.QRect(40, 70, 101, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab2)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 161, 20))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab2)
        self.label_8.setGeometry(QtCore.QRect(10, 300, 161, 20))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(0, 1, 331, 351))
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setDragEnabled(False)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setSortIndicatorShown(False)
        self.line_14 = QtWidgets.QFrame(self.tab)
        self.line_14.setGeometry(QtCore.QRect(350, 110, 351, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(350, 50, 351, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(350, 90, 261, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(350, 70, 261, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(350, 30, 261, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(360, 0, 251, 20))
        self.label_2.setObjectName("label_2")
        self.file_select_button_3 = QtWidgets.QPushButton(self.tab)
        self.file_select_button_3.setGeometry(QtCore.QRect(620, 20, 91, 31))
        self.file_select_button_3.setObjectName("file_select_button_3")
        self.file_select_button_4 = QtWidgets.QPushButton(self.tab)
        self.file_select_button_4.setGeometry(QtCore.QRect(620, 80, 91, 31))
        self.file_select_button_4.setObjectName("file_select_button_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 130, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 320, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 270, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(340, 140, 111, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(440, 150, 20, 211))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(330, 0, 20, 151))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(520, 170, 121, 21))
        self.label_35.setObjectName("label_35")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(510, 230, 171, 21))
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(510, 310, 171, 21))
        self.doubleSpinBox_7.setDecimals(0)
        self.doubleSpinBox_7.setMaximum(100000000000.0)
        self.doubleSpinBox_7.setProperty("value", 1.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(510, 190, 171, 21))
        self.doubleSpinBox_8.setDecimals(6)
        self.doubleSpinBox_8.setMaximum(100000000000.0)
        self.doubleSpinBox_8.setProperty("value", 0.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(510, 290, 171, 21))
        self.label_28.setObjectName("label_28")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(510, 250, 171, 21))
        self.doubleSpinBox_6.setDecimals(6)
        self.doubleSpinBox_6.setMaximum(100000000000.0)
        self.doubleSpinBox_6.setProperty("value", 0.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(340, 220, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(380, 150, 41, 21))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 170, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Start"))
        self.pushButton_8.setText(_translate("MainWindow", "Stop"))
        self.toolButton.setText(_translate("MainWindow", "Connexion"))
        self.label_18.setText(_translate("MainWindow", "Ip adress"))
        self.lineEdit.setText(_translate("MainWindow", "192.168.1.100"))
        self.pushButton_9.setText(_translate("MainWindow", "Pause"))
        self.lineEdit_2.setText(_translate("MainWindow", "data"))
        self.label_3.setText(_translate("MainWindow", "Data file name"))
        self.label_4.setText(_translate("MainWindow", "x"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "|z|"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Arg"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Imag"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Freq (Hz)"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Time (ms)"))
        self.label_5.setText(_translate("MainWindow", "y2"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Arg"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "|z|"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Imag"))
        self.label_6.setText(_translate("MainWindow", "y1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Data logger"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Configurations"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Enable"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Location of the data backup folder</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Location of the configuration backup folder</p></body></html>"))
        self.file_select_button_3.setText(_translate("MainWindow", "Select file"))
        self.file_select_button_4.setText(_translate("MainWindow", "Select file"))
        self.pushButton_2.setText(_translate("MainWindow", "Add acquisition"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove"))
        self.pushButton_4.setText(_translate("MainWindow", "Add mesure"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Maximum duration</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Time between two measurements</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Number of acquisition</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Edit"))
        self.label.setText(_translate("MainWindow", "type"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Impédance"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "VNA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Config acquisition"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
